/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as MinhasCorridasRouteImport } from './routes/minhas-corridas'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RastreioRouteImport } from './routes/rastreio'
import { Route as SejaMotoristaRouteImport } from './routes/seja-motorista'
import { Route as SolicitarRouteImport } from './routes/solicitar'
import { Route as AcompanharTokenRouteImport } from './routes/acompanhar.$token'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdministradoresRouteImport } from './routes/admin/administradores'
import { Route as AdminCorridasRouteImport } from './routes/admin/corridas'
import { Route as AdminIndicacoesRouteImport } from './routes/admin/indicacoes'
import { Route as AdminMotoristasRouteImport } from './routes/admin/motoristas'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminTutoresRouteImport } from './routes/admin/tutores'
import { Route as MinhasCorridasIndexRouteImport } from './routes/minhas-corridas.index'
import { Route as MinhasCorridasRideIdRouteImport } from './routes/minhas-corridas.$rideId'
import { Route as PagamentoRideIdRouteImport } from './routes/pagamento.$rideId'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasCorridasRoute = MinhasCorridasRouteImport.update({
  id: '/minhas-corridas',
  path: '/minhas-corridas',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioRoute = RastreioRouteImport.update({
  id: '/rastreio',
  path: '/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaMotoristaRoute = SejaMotoristaRouteImport.update({
  id: '/seja-motorista',
  path: '/seja-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharTokenRoute = AcompanharTokenRouteImport.update({
  id: '/acompanhar/$token',
  path: '/acompanhar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdministradoresRoute = AdminAdministradoresRouteImport.update({
  id: '/administradores',
  path: '/administradores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCorridasRoute = AdminCorridasRouteImport.update({
  id: '/corridas',
  path: '/corridas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIndicacoesRoute = AdminIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMotoristasRoute = AdminMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTutoresRoute = AdminTutoresRouteImport.update({
  id: '/tutores',
  path: '/tutores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MinhasCorridasIndexRoute = MinhasCorridasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinhasCorridasRoute,
} as any)
const MinhasCorridasRideIdRoute = MinhasCorridasRideIdRouteImport.update({
  id: '/$rideId',
  path: '/$rideId',
  getParentRoute: () => MinhasCorridasRoute,
} as any)
const PagamentoRideIdRoute = PagamentoRideIdRouteImport.update({
  id: '/pagamento/$rideId',
  path: '/pagamento/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/minhas-corridas': typeof MinhasCorridasRouteWithChildren
  '/motorista': typeof MotoristaRoute
  '/perfil': typeof PerfilRoute
  '/rastreio': typeof RastreioRoute
  '/seja-motorista': typeof SejaMotoristaRoute
  '/solicitar': typeof SolicitarRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/corridas': typeof AdminCorridasRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/tutores': typeof AdminTutoresRoute
  '/minhas-corridas/$rideId': typeof MinhasCorridasRideIdRoute
  '/pagamento/$rideId': typeof PagamentoRideIdRoute
  '/admin/': typeof AdminIndexRoute
  '/minhas-corridas/': typeof MinhasCorridasIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/motorista': typeof MotoristaRoute
  '/perfil': typeof PerfilRoute
  '/rastreio': typeof RastreioRoute
  '/seja-motorista': typeof SejaMotoristaRoute
  '/solicitar': typeof SolicitarRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/corridas': typeof AdminCorridasRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/tutores': typeof AdminTutoresRoute
  '/minhas-corridas/$rideId': typeof MinhasCorridasRideIdRoute
  '/pagamento/$rideId': typeof PagamentoRideIdRoute
  '/admin': typeof AdminIndexRoute
  '/minhas-corridas': typeof MinhasCorridasIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/minhas-corridas': typeof MinhasCorridasRouteWithChildren
  '/motorista': typeof MotoristaRoute
  '/perfil': typeof PerfilRoute
  '/rastreio': typeof RastreioRoute
  '/seja-motorista': typeof SejaMotoristaRoute
  '/solicitar': typeof SolicitarRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/corridas': typeof AdminCorridasRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/tutores': typeof AdminTutoresRoute
  '/minhas-corridas/$rideId': typeof MinhasCorridasRideIdRoute
  '/pagamento/$rideId': typeof PagamentoRideIdRoute
  '/admin/': typeof AdminIndexRoute
  '/minhas-corridas/': typeof MinhasCorridasIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/creditos'
    | '/minhas-corridas'
    | '/motorista'
    | '/perfil'
    | '/rastreio'
    | '/seja-motorista'
    | '/solicitar'
    | '/acompanhar/$token'
    | '/admin/administradores'
    | '/admin/corridas'
    | '/admin/indicacoes'
    | '/admin/motoristas'
    | '/admin/relatorios'
    | '/admin/tutores'
    | '/minhas-corridas/$rideId'
    | '/pagamento/$rideId'
    | '/admin/'
    | '/minhas-corridas/'
    | '/api/public/mp-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/creditos'
    | '/motorista'
    | '/perfil'
    | '/rastreio'
    | '/seja-motorista'
    | '/solicitar'
    | '/acompanhar/$token'
    | '/admin/administradores'
    | '/admin/corridas'
    | '/admin/indicacoes'
    | '/admin/motoristas'
    | '/admin/relatorios'
    | '/admin/tutores'
    | '/minhas-corridas/$rideId'
    | '/pagamento/$rideId'
    | '/admin'
    | '/minhas-corridas'
    | '/api/public/mp-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/creditos'
    | '/minhas-corridas'
    | '/motorista'
    | '/perfil'
    | '/rastreio'
    | '/seja-motorista'
    | '/solicitar'
    | '/acompanhar/$token'
    | '/admin/administradores'
    | '/admin/corridas'
    | '/admin/indicacoes'
    | '/admin/motoristas'
    | '/admin/relatorios'
    | '/admin/tutores'
    | '/minhas-corridas/$rideId'
    | '/pagamento/$rideId'
    | '/admin/'
    | '/minhas-corridas/'
    | '/api/public/mp-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CreditosRoute: typeof CreditosRoute
  MinhasCorridasRoute: typeof MinhasCorridasRouteWithChildren
  MotoristaRoute: typeof MotoristaRoute
  PerfilRoute: typeof PerfilRoute
  RastreioRoute: typeof RastreioRoute
  SejaMotoristaRoute: typeof SejaMotoristaRoute
  SolicitarRoute: typeof SolicitarRoute
  AcompanharTokenRoute: typeof AcompanharTokenRoute
  PagamentoRideIdRoute: typeof PagamentoRideIdRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-corridas': {
      id: '/minhas-corridas'
      path: '/minhas-corridas'
      fullPath: '/minhas-corridas'
      preLoaderRoute: typeof MinhasCorridasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio': {
      id: '/rastreio'
      path: '/rastreio'
      fullPath: '/rastreio'
      preLoaderRoute: typeof RastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-motorista': {
      id: '/seja-motorista'
      path: '/seja-motorista'
      fullPath: '/seja-motorista'
      preLoaderRoute: typeof SejaMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar/$token': {
      id: '/acompanhar/$token'
      path: '/acompanhar/$token'
      fullPath: '/acompanhar/$token'
      preLoaderRoute: typeof AcompanharTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/administradores': {
      id: '/admin/administradores'
      path: '/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AdminAdministradoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/corridas': {
      id: '/admin/corridas'
      path: '/corridas'
      fullPath: '/admin/corridas'
      preLoaderRoute: typeof AdminCorridasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/indicacoes': {
      id: '/admin/indicacoes'
      path: '/indicacoes'
      fullPath: '/admin/indicacoes'
      preLoaderRoute: typeof AdminIndicacoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/motoristas': {
      id: '/admin/motoristas'
      path: '/motoristas'
      fullPath: '/admin/motoristas'
      preLoaderRoute: typeof AdminMotoristasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tutores': {
      id: '/admin/tutores'
      path: '/tutores'
      fullPath: '/admin/tutores'
      preLoaderRoute: typeof AdminTutoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/minhas-corridas/': {
      id: '/minhas-corridas/'
      path: '/'
      fullPath: '/minhas-corridas/'
      preLoaderRoute: typeof MinhasCorridasIndexRouteImport
      parentRoute: typeof MinhasCorridasRoute
    }
    '/minhas-corridas/$rideId': {
      id: '/minhas-corridas/$rideId'
      path: '/$rideId'
      fullPath: '/minhas-corridas/$rideId'
      preLoaderRoute: typeof MinhasCorridasRideIdRouteImport
      parentRoute: typeof MinhasCorridasRoute
    }
    '/pagamento/$rideId': {
      id: '/pagamento/$rideId'
      path: '/pagamento/$rideId'
      fullPath: '/pagamento/$rideId'
      preLoaderRoute: typeof PagamentoRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdministradoresRoute: typeof AdminAdministradoresRoute
  AdminCorridasRoute: typeof AdminCorridasRoute
  AdminIndicacoesRoute: typeof AdminIndicacoesRoute
  AdminMotoristasRoute: typeof AdminMotoristasRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminTutoresRoute: typeof AdminTutoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdministradoresRoute: AdminAdministradoresRoute,
  AdminCorridasRoute: AdminCorridasRoute,
  AdminIndicacoesRoute: AdminIndicacoesRoute,
  AdminMotoristasRoute: AdminMotoristasRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminTutoresRoute: AdminTutoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MinhasCorridasRouteChildren {
  MinhasCorridasRideIdRoute: typeof MinhasCorridasRideIdRoute
  MinhasCorridasIndexRoute: typeof MinhasCorridasIndexRoute
}

const MinhasCorridasRouteChildren: MinhasCorridasRouteChildren = {
  MinhasCorridasRideIdRoute: MinhasCorridasRideIdRoute,
  MinhasCorridasIndexRoute: MinhasCorridasIndexRoute,
}

const MinhasCorridasRouteWithChildren = MinhasCorridasRoute._addFileChildren(
  MinhasCorridasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CreditosRoute: CreditosRoute,
  MinhasCorridasRoute: MinhasCorridasRouteWithChildren,
  MotoristaRoute: MotoristaRoute,
  PerfilRoute: PerfilRoute,
  RastreioRoute: RastreioRoute,
  SejaMotoristaRoute: SejaMotoristaRoute,
  SolicitarRoute: SolicitarRoute,
  AcompanharTokenRoute: AcompanharTokenRoute,
  PagamentoRideIdRoute: PagamentoRideIdRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
