/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as MinhasCorridasRouteImport } from './routes/minhas-corridas'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RastreioRouteImport } from './routes/rastreio'
import { Route as SejaMotoristaRouteImport } from './routes/seja-motorista'
import { Route as SolicitarRouteImport } from './routes/solicitar'
import { Route as AcompanharTokenRouteImport } from './routes/acompanhar.$token'
import { Route as AdminMotoristasRouteImport } from './routes/admin/motoristas'
import { Route as PagamentoRideIdRouteImport } from './routes/pagamento.$rideId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasCorridasRoute = MinhasCorridasRouteImport.update({
  id: '/minhas-corridas',
  path: '/minhas-corridas',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioRoute = RastreioRouteImport.update({
  id: '/rastreio',
  path: '/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaMotoristaRoute = SejaMotoristaRouteImport.update({
  id: '/seja-motorista',
  path: '/seja-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharTokenRoute = AcompanharTokenRouteImport.update({
  id: '/acompanhar/$token',
  path: '/acompanhar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMotoristasRoute = AdminMotoristasRouteImport.update({
  id: '/admin/motoristas',
  path: '/admin/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRideIdRoute = PagamentoRideIdRouteImport.update({
  id: '/pagamento/$rideId',
  path: '/pagamento/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/minhas-corridas': typeof MinhasCorridasRoute
  '/motorista': typeof MotoristaRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil': typeof PerfilRoute
  '/rastreio': typeof RastreioRoute
  '/seja-motorista': typeof SejaMotoristaRoute
  '/solicitar': typeof SolicitarRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/pagamento/$rideId': typeof PagamentoRideIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/minhas-corridas': typeof MinhasCorridasRoute
  '/motorista': typeof MotoristaRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil': typeof PerfilRoute
  '/rastreio': typeof RastreioRoute
  '/seja-motorista': typeof SejaMotoristaRoute
  '/solicitar': typeof SolicitarRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/pagamento/$rideId': typeof PagamentoRideIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creditos': typeof CreditosRoute
  '/minhas-corridas': typeof MinhasCorridasRoute
  '/motorista': typeof MotoristaRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil': typeof PerfilRoute
  '/rastreio': typeof RastreioRoute
  '/seja-motorista': typeof SejaMotoristaRoute
  '/solicitar': typeof SolicitarRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/pagamento/$rideId': typeof PagamentoRideIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/creditos'
    | '/minhas-corridas'
    | '/motorista'
    | '/pagamentos'
    | '/perfil'
    | '/rastreio'
    | '/seja-motorista'
    | '/solicitar'
    | '/acompanhar/$token'
    | '/admin/motoristas'
    | '/pagamento/$rideId'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/creditos'
    | '/minhas-corridas'
    | '/motorista'
    | '/pagamentos'
    | '/perfil'
    | '/rastreio'
    | '/seja-motorista'
    | '/solicitar'
    | '/acompanhar/$token'
    | '/admin/motoristas'
    | '/pagamento/$rideId'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/creditos'
    | '/minhas-corridas'
    | '/motorista'
    | '/pagamentos'
    | '/perfil'
    | '/rastreio'
    | '/seja-motorista'
    | '/solicitar'
    | '/acompanhar/$token'
    | '/admin/motoristas'
    | '/pagamento/$rideId'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreditosRoute: typeof CreditosRoute
  MinhasCorridasRoute: typeof MinhasCorridasRoute
  MotoristaRoute: typeof MotoristaRoute
  PagamentosRoute: typeof PagamentosRoute
  PerfilRoute: typeof PerfilRoute
  RastreioRoute: typeof RastreioRoute
  SejaMotoristaRoute: typeof SejaMotoristaRoute
  SolicitarRoute: typeof SolicitarRoute
  AcompanharTokenRoute: typeof AcompanharTokenRoute
  AdminMotoristasRoute: typeof AdminMotoristasRoute
  PagamentoRideIdRoute: typeof PagamentoRideIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-corridas': {
      id: '/minhas-corridas'
      path: '/minhas-corridas'
      fullPath: '/minhas-corridas'
      preLoaderRoute: typeof MinhasCorridasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio': {
      id: '/rastreio'
      path: '/rastreio'
      fullPath: '/rastreio'
      preLoaderRoute: typeof RastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-motorista': {
      id: '/seja-motorista'
      path: '/seja-motorista'
      fullPath: '/seja-motorista'
      preLoaderRoute: typeof SejaMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar/$token': {
      id: '/acompanhar/$token'
      path: '/acompanhar/$token'
      fullPath: '/acompanhar/$token'
      preLoaderRoute: typeof AcompanharTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/motoristas': {
      id: '/admin/motoristas'
      path: '/admin/motoristas'
      fullPath: '/admin/motoristas'
      preLoaderRoute: typeof AdminMotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$rideId': {
      id: '/pagamento/$rideId'
      path: '/pagamento/$rideId'
      fullPath: '/pagamento/$rideId'
      preLoaderRoute: typeof PagamentoRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreditosRoute: CreditosRoute,
  MinhasCorridasRoute: MinhasCorridasRoute,
  MotoristaRoute: MotoristaRoute,
  PagamentosRoute: PagamentosRoute,
  PerfilRoute: PerfilRoute,
  RastreioRoute: RastreioRoute,
  SejaMotoristaRoute: SejaMotoristaRoute,
  SolicitarRoute: SolicitarRoute,
  AcompanharTokenRoute: AcompanharTokenRoute,
  AdminMotoristasRoute: AdminMotoristasRoute,
  PagamentoRideIdRoute: PagamentoRideIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
